/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/underwater.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">

      <group name="Armature_Crab" position={[0, 0, 0]}>
          <primitive object={nodes.Bone001_4} />
          <skinnedMesh
            frustumCulled={false}
            name="Crab"
            geometry={nodes.Crab.geometry}
            material={materials["Material.001"]}
            skeleton={nodes.Crab.skeleton}
          />
        </group>
        
      </group>
    </group>
  );
}

useGLTF.preload("/underwater.glb");
