/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("./meshes/Rock_021.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Rock_021"
        castShadow
        receiveShadow
        geometry={nodes.Rock_021.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("/Rock_021.glb");
