/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { OrbitControls, Stage, Sparkles, MeshWobbleMaterial } from '@react-three/drei'

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function UnderwaterObjects(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./uploads_files_3661723_Tile_pack_environment_4.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        
        {/* <mesh
          name="seaweed016"
          castShadow
          receiveShadow
          geometry={nodes.seaweed016.geometry}
          material={materials.Material}
          position={[95.79, 9.41, -21.73]}
        />
        <mesh
          name="seaweed017"
          castShadow
          receiveShadow
          geometry={nodes.seaweed017.geometry}
          material={materials.Material}
          position={[94.77, 2.87, -12.64]}
        />
        <mesh
          name="seaweed018"
          castShadow
          receiveShadow
          geometry={nodes.seaweed018.geometry}
          material={materials.Material}
          position={[93.76, 3.19, -16.59]}
        />
        <mesh
          name="seaweed019"
          castShadow
          receiveShadow
          geometry={nodes.seaweed019.geometry}
          material={materials.Material}
          position={[97.76, 4.7, -18.07]}
        />
        <mesh
          name="seaweed020"
          castShadow
          receiveShadow
          geometry={nodes.seaweed020.geometry}
          material={materials.Material}
          position={[91.51, 6.72, -20.09]}
        />
        <mesh
          name="seaweed021"
          castShadow
          receiveShadow
          geometry={nodes.seaweed021.geometry}
          material={materials.Material}
          position={[97.08, 5.21, 11.51]}
        />
        <mesh
          name="seaweed022"
          castShadow
          receiveShadow
          geometry={nodes.seaweed022.geometry}
          material={materials.Material}
          position={[88.08, 7.44, 13.24]}
        />
        <mesh
          name="seaweed023"
          castShadow
          receiveShadow
          geometry={nodes.seaweed023.geometry}
          material={materials.Material}
          position={[91.05, 4.52, 13.97]}
        />
        <mesh
          name="seaweed024"
          castShadow
          receiveShadow
          geometry={nodes.seaweed024.geometry}
          material={materials.Material}
          position={[101.23, 10.73, 12.26]}
        />
        <mesh
          name="seaweed025"
          castShadow
          receiveShadow
          geometry={nodes.seaweed025.geometry}
          material={materials.Material}
          position={[108.27, 6.47, -27.23]}
        />
        <mesh
          name="seaweed026"
          castShadow
          receiveShadow
          geometry={nodes.seaweed026.geometry}
          material={materials.Material}
          position={[100.5, 7.19, -8.5]}
        />
        <mesh
          name="seaweed027"
          castShadow
          receiveShadow
          geometry={nodes.seaweed027.geometry}
          material={materials.Material}
          position={[88.86, 6.42, -12.7]}
        />
        <mesh
          name="seaweed028"
          castShadow
          receiveShadow
          geometry={nodes.seaweed028.geometry}
          material={materials.Material}
          position={[113.02, 4.06, -19.85]}
        />
        <mesh
          name="seaweed029"
          castShadow
          receiveShadow
          geometry={nodes.seaweed029.geometry}
          material={materials.Material}
          position={[115, 2.09, -18.2]}
        />
        <mesh
          name="seaweed030"
          castShadow
          receiveShadow
          geometry={nodes.seaweed030.geometry}
          material={materials.Material}
          position={[109.8, 3.86, -21.93]}
        />
        <mesh
          name="seaweed031"
          castShadow
          receiveShadow
          geometry={nodes.seaweed031.geometry}
          material={materials.Material}
          position={[106.34, 6.89, -22.96]}
        />
        <mesh
          name="seaweed032"
          castShadow
          receiveShadow
          geometry={nodes.seaweed032.geometry}
          material={materials.Material}
          position={[104.38, 8.23, -13.78]}
        />
        <mesh
          name="seaweed033"
          castShadow
          receiveShadow
          geometry={nodes.seaweed033.geometry}
          material={materials.Material}
          position={[106.85, 4.57, -18.6]}
        />
        <mesh
          name="seaweed034"
          castShadow
          receiveShadow
          geometry={nodes.seaweed034.geometry}
          material={materials.Material}
          position={[104.98, 4.78, -9.66]}
        />
        <mesh
          name="seaweed035"
          castShadow
          receiveShadow
          geometry={nodes.seaweed035.geometry}
          material={materials.Material}
          position={[106.51, 12.58, -0.79]}
        />
        <mesh
          name="seaweed036"
          castShadow
          receiveShadow
          geometry={nodes.seaweed036.geometry}
          material={materials.Material}
          position={[107.54, 9.51, 0.85]}
        />
        <mesh
          name="seaweed037"
          castShadow
          receiveShadow
          geometry={nodes.seaweed037.geometry}
          material={materials.Material}
          position={[107.32, 6.23, 8.61]}
        />
        <mesh
          name="seaweed038"
          castShadow
          receiveShadow
          geometry={nodes.seaweed038.geometry}
          material={materials.Material}
          position={[104.62, 5.31, 13.9]}
        />
        <mesh
          name="seaweed039"
          castShadow
          receiveShadow
          geometry={nodes.seaweed039.geometry}
          material={materials.Material}
          position={[116.36, 6.47, -3.02]}
        />
        <mesh
          name="seaweed040"
          castShadow
          receiveShadow
          geometry={nodes.seaweed040.geometry}
          material={materials.Material}
          position={[114.01, 4.05, -10.12]}
        />
        <mesh
          name="seaweed041"
          castShadow
          receiveShadow
          geometry={nodes.seaweed041.geometry}
          material={materials.Material}
          position={[91.59, 11.28, -8.08]}
        />
        <mesh
          name="seaweed042"
          castShadow
          receiveShadow
          geometry={nodes.seaweed042.geometry}
          material={materials.Material}
          position={[95.65, 6.58, -7.34]}
        />
        <mesh
          name="seaweed043"
          castShadow
          receiveShadow
          geometry={nodes.seaweed043.geometry}
          material={materials.Material}
          position={[85.54, 6.64, -8.39]}
        />
        <mesh
          name="seaweed044"
          castShadow
          receiveShadow
          geometry={nodes.seaweed044.geometry}
          material={materials.Material}
          position={[83.69, 4.06, -10.62]}
        />
        <mesh
          name="seaweed045"
          castShadow
          receiveShadow
          geometry={nodes.seaweed045.geometry}
          material={materials.Material}
          position={[75.5, 4.7, -13.07]}
        />
        <mesh
          name="seaweed046"
          castShadow
          receiveShadow
          geometry={nodes.seaweed046.geometry}
          material={materials.Material}
          position={[80.18, 6.41, -6.74]}
        />
        <mesh
          name="seaweed047"
          castShadow
          receiveShadow
          geometry={nodes.seaweed047.geometry}
          material={materials.Material}
          position={[55.33, 7.44, 16.8]}
        />
        <mesh
          name="seaweed048"
          castShadow
          receiveShadow
          geometry={nodes.seaweed048.geometry}
          material={materials.Material}
          position={[73.94, 3.89, 20.88]}
        />
        <mesh
          name="seaweed049"
          castShadow
          receiveShadow
          geometry={nodes.seaweed049.geometry}
          material={materials.Material}
          position={[70.55, 6.89, 19.79]}
        />
        <mesh
          name="seaweed050"
          castShadow
          receiveShadow
          geometry={nodes.seaweed050.geometry}
          material={materials.Material}
          position={[61.96, 5.27, 24.68]}
        />
        <mesh
          name="seaweed051"
          castShadow
          receiveShadow
          geometry={nodes.seaweed051.geometry}
          material={materials.Material}
          position={[85.92, 6.99, 19.2]}
        />
        <mesh
          name="seaweed052"
          castShadow
          receiveShadow
          geometry={nodes.seaweed052.geometry}
          material={materials.Material}
          position={[71.05, 5.65, 24.16]}
        />
        <mesh
          name="seaweed053"
          castShadow
          receiveShadow
          geometry={nodes.seaweed053.geometry}
          material={materials.Material}
          position={[52.53, 5.77, 19.37]}
        />
        <mesh
          name="seaweed054"
          castShadow
          receiveShadow
          geometry={nodes.seaweed054.geometry}
          material={materials.Material}
          position={[49.79, 10.26, -9.69]}
        />
        <mesh
          name="seaweed055"
          castShadow
          receiveShadow
          geometry={nodes.seaweed055.geometry}
          material={materials.Material}
          position={[47.89, 5.01, -11.93]}
        />
        <mesh
          name="seaweed056"
          castShadow
          receiveShadow
          geometry={nodes.seaweed056.geometry}
          material={materials.Material}
          position={[50.24, 4.06, 11.22]}
        />
        <mesh
          name="seaweed057"
          castShadow
          receiveShadow
          geometry={nodes.seaweed057.geometry}
          material={materials.Material}
          position={[67.97, 6.39, 1.19]}
        />
        <mesh
          name="seaweed058"
          castShadow
          receiveShadow
          geometry={nodes.seaweed058.geometry}
          material={materials.Material}
          position={[64.64, 3.86, 4.22]}
        />
        <mesh
          name="seaweed059"
          castShadow
          receiveShadow
          geometry={nodes.seaweed059.geometry}
          material={materials.Material}
          position={[126.09, 6.47, -32.7]}
        />
        <mesh
          name="seaweed060"
          castShadow
          receiveShadow
          geometry={nodes.seaweed060.geometry}
          material={materials.Material}
          position={[119.29, 6.89, -40.31]}
        />
        <mesh
          name="seaweed061"
          castShadow
          receiveShadow
          geometry={nodes.seaweed061.geometry}
          material={materials.Material}
          position={[118.07, 6.64, -31.56]}
        />
        <mesh
          name="seaweed062"
          castShadow
          receiveShadow
          geometry={nodes.seaweed062.geometry}
          material={materials.Material}
          position={[108.74, 6.7, -39.07]}
        />
        <mesh
          name="seaweed063"
          castShadow
          receiveShadow
          geometry={nodes.seaweed063.geometry}
          material={materials.Material}
          position={[113.46, 7.19, -25.85]}
        />
        <mesh
          name="seaweed064"
          castShadow
          receiveShadow
          geometry={nodes.seaweed064.geometry}
          material={materials.Material}
          position={[117.93, 4.78, -27.01]}
        />
        <mesh
          name="seaweed065"
          castShadow
          receiveShadow
          geometry={nodes.seaweed065.geometry}
          material={materials.Material}
          position={[126.96, 5.18, -27.46]}
        />
        <mesh
          name="seaweed066"
          castShadow
          receiveShadow
          geometry={nodes.seaweed066.geometry}
          material={materials.Material}
          position={[119.47, 9.18, -18.14]}
        />
        <mesh
          name="seaweed067"
          castShadow
          receiveShadow
          geometry={nodes.seaweed067.geometry}
          material={materials.Material}
          position={[45.03, 8.72, 5.33]}
        />
        <mesh
          name="seaweed068"
          castShadow
          receiveShadow
          geometry={nodes.seaweed068.geometry}
          material={materials.Material}
          position={[38.23, 6.89, -2.24]}
        />
        <mesh
          name="seaweed069"
          castShadow
          receiveShadow
          geometry={nodes.seaweed069.geometry}
          material={materials.Material}
          position={[37.01, 6.18, 6.5]}
        />
        <mesh
          name="seaweed070"
          castShadow
          receiveShadow
          geometry={nodes.seaweed070.geometry}
          material={materials.Material}
          position={[27.69, 6.05, -1]}
        />
        <mesh
          name="seaweed071"
          castShadow
          receiveShadow
          geometry={nodes.seaweed071.geometry}
          material={materials.Material}
          position={[32.4, 5.86, 12.21]}
        />
        <mesh
          name="seaweed072"
          castShadow
          receiveShadow
          geometry={nodes.seaweed072.geometry}
          material={materials.Material}
          position={[37.02, 4.35, 10.33]}
        />
        <mesh
          name="seaweed073"
          castShadow
          receiveShadow
          geometry={nodes.seaweed073.geometry}
          material={materials.Material}
          position={[41.69, 5.7, 7.42]}
        />
        <mesh
          name="seaweed074"
          castShadow
          receiveShadow
          geometry={nodes.seaweed074.geometry}
          material={materials.Material}
          position={[34.81, 5.87, 20.85]}
        />
        <mesh
          name="seaweed075"
          castShadow
          receiveShadow
          geometry={nodes.seaweed075.geometry}
          material={materials.Material}
          position={[49.38, 10.11, -27.72]}
        />
        <mesh
          name="seaweed076"
          castShadow
          receiveShadow
          geometry={nodes.seaweed076.geometry}
          material={materials.Material}
          position={[36.6, 5.69, -40.26]}
        />
        <mesh
          name="seaweed077"
          castShadow
          receiveShadow
          geometry={nodes.seaweed077.geometry}
          material={materials.Material}
          position={[35.99, 5.64, -31.64]}
        />
        <mesh
          name="seaweed078"
          castShadow
          receiveShadow
          geometry={nodes.seaweed078.geometry}
          material={materials.Material}
          position={[26.06, 5.03, -39.02]}
        />
        <mesh
          name="seaweed079"
          castShadow
          receiveShadow
          geometry={nodes.seaweed079.geometry}
          material={materials.Material}
          position={[72.38, 6.31, -25.81]}
        />
        <mesh
          name="seaweed080"
          castShadow
          receiveShadow
          geometry={nodes.seaweed080.geometry}
          material={materials.Material}
          position={[76.85, 6.47, -26.96]}
        />
        <mesh
          name="seaweed081"
          castShadow
          receiveShadow
          geometry={nodes.seaweed081.geometry}
          material={materials.Material}
          position={[85.89, 4.05, -27.42]}
        />
        <mesh
          name="seaweed082"
          castShadow
          receiveShadow
          geometry={nodes.seaweed082.geometry}
          material={materials.Material}
          position={[74.02, 5.73, -33.88]}
        />
        <mesh
          name="seaweed083"
          castShadow
          receiveShadow
          geometry={nodes.seaweed083.geometry}
          material={materials.Material}
          position={[139.4, 6.22, -11.46]}
        />
        <mesh
          name="seaweed084"
          castShadow
          receiveShadow
          geometry={nodes.seaweed084.geometry}
          material={materials.Material}
          position={[133.96, 5.11, -3.42]}
        />
        <mesh
          name="seaweed085"
          castShadow
          receiveShadow
          geometry={nodes.seaweed085.geometry}
          material={materials.Material}
          position={[136.31, 5.65, 3.67]}
        />
        <mesh
          name="seaweed086"
          castShadow
          receiveShadow
          geometry={nodes.seaweed086.geometry}
          material={materials.Material}
          position={[133.04, 6.17, -8.55]}
        />
        <mesh
          name="seaweed087"
          castShadow
          receiveShadow
          geometry={nodes.seaweed087.geometry}
          material={materials.Material}
          position={[126.29, 6.67, -16.27]}
        />
        <mesh
          name="seaweed088"
          castShadow
          receiveShadow
          geometry={nodes.seaweed088.geometry}
          material={materials.Material}
          position={[125.08, 6.64, -7.52]}
        />
        <mesh
          name="seaweed089"
          castShadow
          receiveShadow
          geometry={nodes.seaweed089.geometry}
          material={materials.Material}
          position={[120.23, 2.89, -15.91]}
        />
        <mesh
          name="seaweed090"
          castShadow
          receiveShadow
          geometry={nodes.seaweed090.geometry}
          material={materials.Material}
          position={[115.75, 5.17, -15.03]}
        />
        <mesh
          name="seaweed091"
          castShadow
          receiveShadow
          geometry={nodes.seaweed091.geometry}
          material={materials.Material}
          position={[107.62, 6.05, -12.01]}
        />
        <mesh
          name="seaweed092"
          castShadow
          receiveShadow
          geometry={nodes.seaweed092.geometry}
          material={materials.Material}
          position={[111.47, 7.88, -13.4]}
        />
        <mesh
          name="seaweed093"
          castShadow
          receiveShadow
          geometry={nodes.seaweed093.geometry}
          material={materials.Material}
          position={[114.72, 2.25, -5.95]}
        />
        <mesh
          name="seaweed094"
          castShadow
          receiveShadow
          geometry={nodes.seaweed094.geometry}
          material={materials.Material}
          position={[120.46, 8.07, -1.81]}
        />
        <mesh
          name="seaweed095"
          castShadow
          receiveShadow
          geometry={nodes.seaweed095.geometry}
          material={materials.Material}
          position={[99.04, 10.42, -26.97]}
        />
        <mesh
          name="seaweed096"
          castShadow
          receiveShadow
          geometry={nodes.seaweed096.geometry}
          material={materials.Material}
          position={[116.47, 6.47, 20.63]}
        />
        <mesh
          name="seaweed097"
          castShadow
          receiveShadow
          geometry={nodes.seaweed097.geometry}
          material={materials.Material}
          position={[102.68, 6.89, 18.27]}
        />
        <mesh
          name="seaweed098"
          castShadow
          receiveShadow
          geometry={nodes.seaweed098.geometry}
          material={materials.Material}
          position={[81.95, 4.42, 32.65]}
        />
        <mesh
          name="seaweed099"
          castShadow
          receiveShadow
          geometry={nodes.seaweed099.geometry}
          material={materials.Material}
          position={[77.5, 7.42, 33.81]}
        />
        <mesh
          name="seaweed100"
          castShadow
          receiveShadow
          geometry={nodes.seaweed100.geometry}
          material={materials.Material}
          position={[92.13, 8.63, 19.5]}
        />
        <mesh
          name="seaweed101"
          castShadow
          receiveShadow
          geometry={nodes.seaweed101.geometry}
          material={materials.Material}
          position={[88.56, 8.76, 24.93]}
        />
        <mesh
          name="seaweed102"
          castShadow
          receiveShadow
          geometry={nodes.seaweed102.geometry}
          material={materials.Material}
          position={[93.19, 5.21, 28.86]}
        />
        <mesh
          name="seaweed103"
          castShadow
          receiveShadow
          geometry={nodes.seaweed103.geometry}
          material={materials.Material}
          position={[97.52, 5.38, 29.48]}
        />
        <mesh
          name="seaweed104"
          castShadow
          receiveShadow
          geometry={nodes.seaweed104.geometry}
          material={materials.Material}
          position={[64.93, 2.63, -27.25]}
        />
        <mesh
          name="seaweed105"
          castShadow
          receiveShadow
          geometry={nodes.seaweed105.geometry}
          material={materials.Material}
          position={[55.8, 6.64, 37.02]}
        />
        <mesh
          name="seaweed106"
          castShadow
          receiveShadow
          geometry={nodes.seaweed106.geometry}
          material={materials.Material}
          position={[103.75, 6.64, 39.34]}
        />
        <mesh
          name="seaweed107"
          castShadow
          receiveShadow
          geometry={nodes.seaweed107.geometry}
          material={materials.Material}
          position={[36.28, 8.48, -8.24]}
        />
        <mesh
          name="seaweed108"
          castShadow
          receiveShadow
          geometry={nodes.seaweed108.geometry}
          material={materials.Material}
          position={[39.88, 6.5, 16.33]}
        />
        <mesh
          name="seaweed109"
          castShadow
          receiveShadow
          geometry={nodes.seaweed109.geometry}
          material={materials.Material}
          position={[41.79, 5.18, 17.1]}
        />
        <mesh
          name="seaweed110"
          castShadow
          receiveShadow
          geometry={nodes.seaweed110.geometry}
          material={materials.Material}
          position={[40.18, 6.8, 18.73]}
        />
        <mesh
          name="seaweed111"
          castShadow
          receiveShadow
          geometry={nodes.seaweed111.geometry}
          material={materials.Material}
          position={[93.41, 10.47, 38.93]}
          rotation={[Math.PI, -1.5, Math.PI]}
        />
        <mesh
          name="seaweed112"
          castShadow
          receiveShadow
          geometry={nodes.seaweed112.geometry}
          material={materials.Material}
          position={[136.59, 7.58, -40]}
          rotation={[Math.PI, -0.33, Math.PI]}
        />
        <mesh
          name="seaweed113"
          castShadow
          receiveShadow
          geometry={nodes.seaweed113.geometry}
          material={materials.Material}
          position={[140.23, 7.71, -33.62]}
          rotation={[Math.PI, -0.33, Math.PI]}
        />
        <mesh
          name="seaweed114"
          castShadow
          receiveShadow
          geometry={nodes.seaweed114.geometry}
          material={materials.Material}
          position={[141.71, 7.71, -16.03]}
          rotation={[-Math.PI, 0.23, -Math.PI]}
        />
        <mesh
          name="seaweed115"
          castShadow
          receiveShadow
          geometry={nodes.seaweed115.geometry}
          material={materials.Material}
          position={[138.82, 7.58, -7.36]}
          rotation={[-Math.PI, 0.01, -Math.PI]}
        />
        <mesh
          name="seaweed116"
          castShadow
          receiveShadow
          geometry={nodes.seaweed116.geometry}
          material={materials.Material}
          position={[139.72, 7.71, 11.67]}
          rotation={[-Math.PI, 0.69, -Math.PI]}
        />
        <mesh
          name="seaweed117"
          castShadow
          receiveShadow
          geometry={nodes.seaweed117.geometry}
          material={materials.Material}
          position={[142.07, 7.71, 29.8]}
          rotation={[-Math.PI, 0.21, -Math.PI]}
        />
        <mesh
          name="seaweed118"
          castShadow
          receiveShadow
          geometry={nodes.seaweed118.geometry}
          material={materials.Material}
          position={[110.87, 10.33, 40.33]}
          rotation={[Math.PI, -1.15, Math.PI]}
        />
        <mesh
          name="seaweed119"
          castShadow
          receiveShadow
          geometry={nodes.seaweed119.geometry}
          material={materials.Material}
          position={[52.34, 10.33, 41.83]}
          rotation={[Math.PI, -1.41, Math.PI]}
        />
        <mesh
          name="seaweed120"
          castShadow
          receiveShadow
          geometry={nodes.seaweed120.geometry}
          material={materials.Material}
          position={[64.13, 10.47, 43]}
          rotation={[Math.PI, -1.41, Math.PI]}
        />
        <mesh
          name="seaweed121"
          castShadow
          receiveShadow
          geometry={nodes.seaweed121.geometry}
          material={materials.Material}
          position={[31.56, 10.47, -42.85]}
          rotation={[Math.PI, -1.41, Math.PI]}
        />
        <mesh
          name="seaweed122"
          castShadow
          receiveShadow
          geometry={nodes.seaweed122.geometry}
          material={materials.Material}
          position={[36.74, 6.47, -36.06]}
          rotation={[Math.PI, -1.41, Math.PI]}
        />
        <mesh
          name="seaweed123"
          castShadow
          receiveShadow
          geometry={nodes.seaweed123.geometry}
          material={materials.Material}
          position={[44.08, 10.47, -36.26]}
          rotation={[Math.PI, -1.41, Math.PI]}
        />
        <mesh
          name="seaweed124"
          castShadow
          receiveShadow
          geometry={nodes.seaweed124.geometry}
          material={materials.Material}
          position={[60.91, 10.33, -36.94]}
          rotation={[Math.PI, -1.41, Math.PI]}
        />
        <mesh
          name="seaweed125"
          castShadow
          receiveShadow
          geometry={nodes.seaweed125.geometry}
          material={materials.Material}
          position={[68.25, 10.47, -37.14]}
          rotation={[Math.PI, -1.41, Math.PI]}
        />
        <mesh
          name="seaweed126"
          castShadow
          receiveShadow
          geometry={nodes.seaweed126.geometry}
          material={materials.Material}
          position={[85.07, 10.33, -39.13]}
          rotation={[Math.PI, -1.41, Math.PI]}
        />
        <mesh
          name="seaweed127"
          castShadow
          receiveShadow
          geometry={nodes.seaweed127.geometry}
          material={materials.Material}
          position={[93.19, 7.25, -39.83]}
          rotation={[Math.PI, -1.41, Math.PI]}
        />
        <mesh
          name="seaweed128"
          castShadow
          receiveShadow
          geometry={nodes.seaweed128.geometry}
          material={materials.Material}
          position={[95.83, 7.16, -41.5]}
          rotation={[Math.PI, -1.41, Math.PI]}
        />
        <mesh
          name="seaweed129"
          castShadow
          receiveShadow
          geometry={nodes.seaweed129.geometry}
          material={materials.Material}
          position={[103.95, 6.6, -42.19]}
          rotation={[Math.PI, -1.41, Math.PI]}
        /> */}
        <mesh
          name="seaweed130"
          castShadow
          receiveShadow
          geometry={nodes.seaweed130.geometry}
          material={materials.Material}
          position={[22.17, 7.7, -21.03]}
          rotation={[-Math.PI, 0.1, -Math.PI]}
        />
        
      </group>
    </group>
  );
}

useGLTF.preload("/uploads_files_3661723_Tile_pack_environment_4.glb");
